### ISSUE TITLE
Cards don't show up

### ISSUE THREAD

**Issue by marked0ne** [im-mi/KoiCatalog#4]
Basically, this is how KoiCatalog looks after choosing a directory:
![untitled](https://user-images.githubusercontent.com/20538693/45635425-3799da00-baa5-11e8-87ad-b345dfe61557.png)

Refresh and rebuilding doesn't fix the problem.

Edit: Version 1.0 works without issues.

**Comment by im-mi** [comment]
Thanks for the bug report!

Can you post a screenshot of the stats tab? Maybe we can use that to narrow down what the problem is.

**Comment by marked0ne** [comment]
Sure, here it is:
![untitled](https://user-images.githubusercontent.com/20538693/45676267-a1f85c00-bb31-11e8-81d0-0b9442a64c63.png)

**Comment by im-mi** [comment]
Thanks. That's been really helpful for narrowing down the issue.

Based on your help I think the Koikatu character card loader is failing somehow. To figure out why, I've put up a pre-release build with some extra error-reporting functionality. Using that build, if a file fails to load, it should show more information about why in the event log.

If you (or anyone else with this issue) are interested, could you try it out and post a screenshot of what appears in the event log after rebuilding the database? It would be greatly appreciated. By the way, you can open the event log by selecting [Database > Event Log] in the menu.

The pre-release build is available for download from here: https://github.com/im-mi/KoiCatalog/releases/tag/1.1.1

**Comment by cm3d-legacy** [comment]
Hi. I got same problem and here is the screenshot.
![snap](https://user-images.githubusercontent.com/14005752/47848797-ca52c600-de12-11e8-886c-d68e210fd2b3.png)

**Comment by im-mi** [comment]
@cm3d-legacy 
Thanks for the help. It looks like there's nothing unusual in the log, though, so I'm at a loss here.

**Comment by cm3d-legacy** [comment]
@im-mi 
1.0 is works perfect but 1.1 and 1.1.1 just...
btw 1.1 and 1.1.1 not showing my default directories at start page.
I hope this helps.

**Comment by im-mi** [comment]
> btw 1.1 and 1.1.1 not showing my default directories at start page.
> I hope this helps.

That makes it sound like the Koikatu plugin isn't working in general, or isn't being loaded at all. That said, it gives me an idea for a fix which is now in the new prerelease build.

For anyone who wants to try it, the new prerelease build is available at the same location: https://github.com/im-mi/KoiCatalog/releases/tag/1.1.1

**Comment by im-mi** [comment]
I still haven't been able to reproduce this myself, so if anyone with this issue would test the new build and post the results it would be greatly appreciated.

**Comment by cm3d-legacy** [comment]
@im-mi 
Hi! I tried 1.1.1 PreRelease.2 and it works for me.

**Comment by im-mi** [comment]
@cm3d-legacy Awesome. Sounds like that fixed it.
