### ISSUE TITLE
Drag and drop issue when space in file path

### ISSUE THREAD

**Issue by Tina-otoge** [im-mi/KoiCatalog#6]
If the file path has spaces in it, spaces apparently get converted to their encoded counterpart (%20) when dragging them to the game, and the game will complain with a not found error.

When dragging in the same card but from Windows file explorer, it works fine.

The problem occurs wherever spaces appear in the path.

I like to rename my cards with more readable names, also thankfully my cards are stored in a folder with no spaces in the name right now, but that my change in the future as I add more cards and need to sort them in different folders.

Could you look into this?

**Comment by im-mi** [comment]
Thanks for the bug report. It should be fixed in the latest version which is available at the [releases page ](https://github.com/im-mi/KoiCatalog/releases).

--

Fixed by https://github.com/im-mi/KoiCatalog/commit/6cf2f945572ba7d65b475f6b33aa3e50fe66bd69
